CREATE TABLE PROJECT (
id INT NOT NULL AUTO_INCREMENT(1000),
name VARCHAR(100) NOT NULL,
PRIMARY KEY (id)
);

CREATE TABLE MEMBER (
    id INT NOT NULL AUTO_INCREMENT(9000),
    name VARCHAR(100) NOT NULL,
    project_id INT NOT NULL,
    PRIMARY KEY (id),
    FOREIGN KEY (project_id) REFERENCES Project(id)
);

CREATE TABLE REQUIREMENT (
	requirement VARCHAR(100) NOT NULL,
	project_id INT NOT NULL,
	FOREIGN KEY (project_id) REFERENCES Project(id)
);